Docs/2_4 upgrade
bandprotocol/bandchain-docs-archived pull request #112
Opened 2022-11-16 08:13 UTC by colmazia

2022-11-21 06:30 UTC, babybunn approved these changes

2022-11-21 08:33 UTC, taobun commented
Did we have format config? @babybunn

2022-11-21 10:01 UTC, RogerKSI requested changes

2022-11-21 10:01 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-validator-using-statesync.md
> +export SEEDS="<SEED>,<SEED>,..."
please add example

2022-11-21 10:05 UTC, RogerKSI requested changes

2022-11-21 10:05 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-validator-using-statesync.md
> +git clone https://github.com/bandprotocol/chain
add cd ~

2022-11-21 13:37 UTC, babybunn commented
> Did we have format config? @babybunn

I already added the formatter config to the branch @colmazia please check

2022-11-22 18:31 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-validator-using-statesync.md
> +You have to have at least 32 GB of RAM to using State Sync
should be "to use"?

2022-11-22 18:33 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-validator.md
> +# e.g. SEEDS="8d42bdcb6cced03e0b67fa3957e4e9c8fd89015a@34.87.86.195:26656,543e0cab9c3016a0e99775443a17bcf163038912@34.150.156.78:26656"
I think e.g. comment should come before the command but up to you krub.

2022-11-22 18:48 UTC, RogerKSI requested changes

2022-11-22 18:48 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-validator-using-statesync.md
> +
no empty line.

2022-11-22 18:48 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-validator-using-statesync.md
> +<!--
Will the filename be the section name? should we align it with testnet file?

2022-11-22 18:48 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-validator-using-statesync.md
> +TRUST_HASH=$(curl -s "http://rpc.laozi1.bandchain.org/block?height=$TRUST_HEIGHT" | jq -r .result.block_id.hash)
sry, please change it to laozi4.
- it's https.
- it's full rest.

2022-11-22 18:48 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-validator-using-statesync.md
> +    "/\[statesync\]/,+34 s/rpc_servers = \".*\"/rpc_servers = \"http\:\/\/rpc.laozi1.bandchain.org\:80,http\:\/\/rpc.laozi2.bandchain.org\:80,https\:\/\/rpc.laozi3.bandchain.org\:80,https\:\/\/rpc.la
for 3,4, port should be 443.

2022-11-22 18:48 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-validator-using-statesync.md
> +[Service]
add empty line between section (unit<->service, service<->install) to align with yoda service.

2022-11-22 18:48 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-validator-using-statesync.md
> +sudo apt-get install -y build-essential curl wget
install jq as well.

2022-11-23 07:38 UTC, colmazia commented on docs/joining-mainnet/join-as-a-validator-using-statesync.md
> +You have to have at least 32 GB of RAM to using State Sync
oh don't deserve G4

2022-11-23 07:47 UTC, colmazia commented on docs/joining-mainnet/join-as-a-validator-using-statesync.md
> +sudo apt-get install -y build-essential curl wget
wow nice catch

2022-11-24 18:38 UTC, RogerKSI requested changes

2022-11-24 18:38 UTC, RogerKSI commented on docs/joining-testnet/join-as-a-testnet-validator.md
> +In this section, we'll explain the requirements and basics for running your own BandChain testnet#6 validator node and syncing from the starting block. If you want to join using State Sync or Quick S
no quick sync for testnet.

2022-11-28 04:18 UTC, RogerKSI approved these changes

2022-11-28 06:23 UTC, merged