Create docs join-as-a-mainnet-validator-using-snapshots.md
bandprotocol/bandchain-docs-archived pull request #122
Opened 2022-12-28 08:09 UTC by satawatnack

2023-01-06 04:22 UTC, RogerKSI requested changes

2023-01-06 04:22 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-mainnet-validator-using-snapshots.md
> +URL=`curl -L https://quicksync.io/band.json|jq -r '.[] |select(.file=="laozi-mainnet-pruned")|.url'`
validator can choose the type of snapshot (pruned/default). think need to give information more a bit.

2023-01-06 04:22 UTC, RogerKSI commented on docs/joining-mainnet/join-as-a-mainnet-validator-using-snapshots.md
> +curl -s https://lcd-cosmos.cosmostation.io/txs/`curl -s $URL.hash`|jq -r '.tx.value.memo'|sha512sum -c
this lcd-cosmos still works, right? last time, it seems can't get the hash.

2023-01-09 07:57 UTC, taobun requested changes

2023-01-09 07:57 UTC, taobun commented on docs/joining-mainnet/join-as-a-mainnet-validator-using-snapshots-chainlayer.md
> +You can choose `laozi-mainnet-pruned` size 144G or `laozi-mainnet-default` size 1.8T
100-200 GB (prune) and ~2TB

2023-01-11 03:42 UTC, colmazia commented
Does we gonna continue doing p’Bun idea mai na, about unifying all of validator-joining docs

2023-01-11 03:50 UTC, colmazia reviewed
Does we gonna continue doing p’Bun idea mai na, about unifying all of validator-joining docs

2023-01-11 04:25 UTC, RogerKSI commented
As we decided to use tabs to reduce duplicated content, I have moved the content here with the tab section to the new PR. please review there instead (https://github.com/bandprotocol/bandchain-docs/pull/125).

2023-01-11 04:26 UTC, closed without merging