Add data source section
bandprotocol/bandchain-docs-archived pull request #28
Opened 2021-09-17 09:50 UTC by traviolus

2021-09-17 10:40 UTC, prin-r commented on docs/data-provider/data-source/introduction.md
> +
should add that the ds is executed off-chain in order to reduce on-chain workload as some tasks cannot be performed on the chain such as heavy computation or anything that takes a long time (network latency, ...).

2021-09-17 15:39 UTC, traviolus commented on docs/data-provider/data-source/introduction.md
> +
Done! 🙏🏻

2021-09-18 07:32 UTC, prin-r commented on docs/data-provider/data-source/implementation.md
> +```python
1. I think we should make the ds and the os have some relationship with each other.
2. This sample ds takes no input at all, which makes me think that we should add some input to it.
3. I'm currently making an example os with inputs and outputs like this -> {symbol:string,multiplier:u64}/{value:u64}.

2021-09-18 07:35 UTC, traviolus commented on docs/data-provider/data-source/implementation.md
> +```python
Agree with you on this point and I already stated about arguments in the second example. [Total token supply]

2021-09-18 07:55 UTC, prin-r commented on docs/data-provider/data-source/implementation.md
> +```python
Ok then I will use the second ds to continue with the os example

2021-09-21 15:42 UTC, cathtunti requested changes

2021-09-21 15:42 UTC, cathtunti commented on docs/data-provider/data-source/introduction.md
> +Permissionless API means that they are openly available to anyone who might want to audit the data source, any
Permissionless APIs are openly available...

2021-09-21 15:42 UTC, cathtunti commented on docs/data-provider/data-source/introduction.md
> +Permissionless API means that they are openly available to anyone who might want to audit the data source, any
or

2021-09-21 15:42 UTC, cathtunti commented on docs/data-provider/data-source/deployment.md
> +Note that the sender who creates the data source and the owner of the data source does not need to be the same.
Note that the sender who creates the data source and the owner of the data source do not need to be the same.

2021-09-21 15:42 UTC, cathtunti commented on docs/data-provider/data-source/deployment.md
> +In the case of unowned data sources, it is the data source's configuration on BandChain that cannot be changed.
didn't we already say this in line 34-35?

2021-09-22 13:49 UTC, merged